baseURL = 'https://jayelamos.com/'
languageCode = 'es'
title = 'jaYelamos'
theme = 'friend-ng'
enableSharingButtons = true

[[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

[[params.social]]
  name = "twitter"
  url = "https://x.com/s1nf1l"

[[params.social]]
  name = "mastodon"
  url = "https://mastodon.social/@s1nf1l"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/jose-antonio-y%C3%A9lamos-reyes-1106a7a7/"

  [[params.social]]
  name = "email"
  url = "mailto:jayelamos@protonmail.com"